# Generated by Django 3.1.3 on 2020-11-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201115_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
