# Generated by Django 3.1.3 on 2020-11-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201123_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseShots',
        ),
    ]
