# Generated by Django 3.1.3 on 2020-11-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_delete_courseshots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
