# Generated by Django 3.1.3 on 2020-11-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_articlestatistic_temporarybanip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestatistic',
            name='article',
        ),
        migrations.DeleteModel(
            name='TemporaryBanIp',
        ),
        migrations.DeleteModel(
            name='ArticleStatistic',
        ),
    ]
